import type { MetadataRoute } from 'next'

const BASE_URL = 'https://elbil.io'

// All pillar pages
const pillarPages = [
  '',
  'elbil',
  'hva-er-elbil',
  'beste-elbil',
  'elbil-lading',
  'elbil-kostnader',
  'elbil-rekkevidde',
  'om-oss',
  'slik-jobber-vi',
  'verktoy/ladekalkulator',
  'verktoy/besparelseskalkulator',
  'verktoy/rekkevidde',
]

// Core cluster pages
const clusterPages = [
  'hvordan-lade-elbil',
  'hvordan-lade-elbil-hjemme',
  'hurtiglading-elbil',
  'ladepris-elbil',
  'hva-koster-elbil',
  'hva-koster-lading',
  'hvor-mye-sparer-man-pa-elbil',
  'hvilken-elbil-skal-jeg-velge',
  'beste-elbil-2026',
  'elbil-familiebil',
  'batteri-elbil',
  'hvor-lenge-varer-elbil',
]

// All /artikler/ slugs
const artikler = [
  'lade-elbil-i-kulde',
  'ladekabel-elbil-guide',
  'type-2-lading',
  'ccs-hurtiglading',
  'chademo-lading',
  'lade-elbil-pa-hytta',
  'lade-elbil-i-borettslag',
  'lade-elbil-pa-jobb',
  'ladestasjon-hjemme-pris',
  'beste-hjemmelader-elbil',
  'installere-lader-elbil',
  'enova-stotte-elbillader',
  'ladeoperatorer-norge',
  'ladekort-elbil',
  'lade-elbil-i-europa',
  'ladenettverk-norge',
  'ladeeffekt-kw-forklart',
  'hvor-mange-kwh-lade-elbil',
  'ladetid-elbil',
  'stikkontakt-lading-elbil',
  'ladeplanlegger-elbil',
  'lading-elbil-vinter',
  'smartlading-elbil',
  'solcelle-lading-elbil',
  'trefase-lading-elbil',
  'lading-leilighet-elbil',
  'elbil-lading-app',
  'gratis-lading-elbil',
  'elbil-lading-pris-per-kwh',
  'lade-elbil-tilhenger',
  'vehicle-to-grid-norge',
  'dc-lading-vs-ac-lading',
  'elbil-ladehastighet-tabell',
  'lade-elbil-regn',
  'elbil-vs-fossilbil-kostnad',
  'elbil-forsikring-pris',
  'elbil-avgifter-norge',
  'elbil-moms-2026',
  'elbil-bompenger',
  'elbil-parkering-fordeler',
  'elbil-ferge-rabatt',
  'elbil-firmabil',
  'elbil-skatt-fordeler',
  'elbil-drivstoffkostnad',
  'elbil-vedlikehold-kostnad',
  'elbil-dekkbytte-pris',
  'elbil-verditap',
  'billigste-elbil-norge',
  'elbil-bruktbil-pris',
  'elbil-leasing-vs-kjop',
  'elbil-finansiering',
  'elbil-stromforbruk-per-mil',
  'elbil-arsavgift',
  'elbil-eu-kontroll',
  'elbil-service-intervall',
  'elbil-batteribytte-kostnad',
  'elbil-totalkostand-kalkulator',
  'elbil-veihjelp-priser',
  'elbil-tilhengerloype-kostnad',
  'elbil-piggdekk-priser',
  'elbil-forbruk-motorvei',
  'elbil-stromavtale-tips',
  'elbil-kost-nytte-analyse',
  'beste-elbil-suv',
  'beste-liten-elbil',
  'beste-elbil-lang-rekkevidde',
  'elbil-for-pendlere',
  'elbil-for-langtur',
  'elbil-for-vinter',
  'elbil-for-fjellvei',
  'elbil-under-300000',
  'elbil-under-400000',
  'elbil-under-500000',
  'elbil-stasjonsvogn',
  'elbil-7-seter',
  'elbil-firehjulstrekk',
  'elbil-tilhengervekt',
  'elbil-bagasjeplass',
  'tesla-model-y-test',
  'volkswagen-id4-test',
  'volvo-ex30-test',
  'skoda-enyaq-test',
  'byd-atto3-test',
  'hyundai-ioniq5-test',
  'kia-ev6-test',
  'mercedes-eqb-test',
  'toyota-bz4x-test',
  'nio-el8-test',
  'polestar-2-test',
  'bmw-ix3-test',
  'ford-mustang-mach-e-test',
  'audi-q4-etron-test',
  'elbil-kinesiske-merker',
  'elbil-sammenligning-verktoy',
  'elbil-nybil-vs-bruktbil',
  'elbil-for-eldre',
  'elbil-for-unge-forere',
  'elbil-for-hytte',
  'elbil-pickup-norge',
  'elbil-motor-forklart',
  'elbil-regenerering',
  'elbil-varmepumpe',
  'elbil-batteriteknologi',
  'elbil-batterikapasitet-kwh',
  'elbil-batteri-degradering',
  'elbil-batteri-garanti',
  'elbil-rekkevidde-vinter',
  'elbil-rekkevidde-motorvei',
  'wltp-vs-reell-rekkevidde',
  'elbil-topphastighet',
  'elbil-akselerasjon',
  'elbil-firehjulsdrift-teknikk',
  'elbil-software-oppdatering',
  'elbil-dekkslitasje',
  'elbil-bremser-vedlikehold',
  'elbil-lydniva',
  'elbil-sikkerhet-ncap',
  'elbil-krocktest',
  'solid-state-batteri',
  'elbil-intelligent-fartsholder',
  'elbil-ota-oppdatering',
  'elbil-aerodynamikk',
  'natrium-ion-batteri-elbil',
  'elbil-kjolingsystem',
  'elbil-rekkeviddeangst',
  'elbil-motortyper',
  'elbil-energiforbruk-kwh-mil',
  'elbil-pre-conditioning',
  'elbil-batteriresirkulering',
  'elbil-miljo-fordeler',
  'elbil-co2-utslipp',
  'elbil-vs-hydrogen',
  'elbil-produksjon-miljo',
  'elbil-stromkilde-norge',
  'elbil-gruvedrift-litium',
  'elbil-resirkulering',
  'elbil-livssyklus',
  'elbil-stoy-byliv',
  'elbil-lokal-luftkvalitet',
  'elbil-klimaregnskap',
  'elbil-norges-klimamal',
  'elbil-europa-utslipp',
  'elbil-fornybar-energi',
  'elbil-biodrivstoff-sammenligning',
  'elbil-micro-plast-dekk',
  'elbil-energieffektivitet',
  'batteripass-eu-elbil',
  'elbil-langtur-norge',
  'elbil-langtur-europa',
  'elbil-vinter-tips',
  'elbil-fjellovergang',
  'elbil-nordnorge',
  'elbil-hytteveien',
  'elbil-camping',
  'elbil-takstativ-forbruk',
  'elbil-tilhenger-rekkevidde',
  'elbil-barnesete-plass',
  'elbil-hund',
  'elbil-daglig-bruk',
  'elbil-pendling',
  'elbil-kjoretips',
  'elbil-vedlikeholdsguide',
  'elbil-forsikring-tips',
  'elbil-bruktbil-sjekkliste',
  'elbil-garanti-oversikt',
  'elbil-veihjelp-tips',
  'elbil-trafikkregler',
  'elbil-kjorestil',
  'elbil-app-oversikt',
  'elbil-bildeling',
  'elbil-taxi',
  'elbil-varebil',
  'elbil-bobil',
  'elbil-mc',
  'elbil-sparkesykkel-regler',
  'elbil-elsykkel-lading',
  'elbil-for-funksjonshemmede',
  'elbil-norge-statistikk',
  'elbil-markedsandel-norge',
  'elbil-politikk-norge',
  'elbil-avgiftsfritak-historie',
  'elbil-eu-regulering',
  'elbil-forbud-fossilbil',
  'elbil-autonom-kjoring',
  'elbil-v2g-fremtid',
  'elbil-batteribytte-stasjon',
  'elbil-induksjonsladning',
  'elbil-salg-norge-historikk',
  'elbil-infrastruktur-utbygging',
  'elbil-stromnett-belastning',
  'elbil-2030-prognose',
  'elbil-land-sammenligning',
  'elbil-kina-utvikling',
  'elbil-usa-marked',
  'elbil-flygende-biler',
  'elbil-tungtransport',
  'elbil-rettferdig-omstilling',
  'er-elbil-farlig',
  'elbil-brann-risiko',
  'elbil-myter',
  'elbil-i-tunnel',
  'elbil-stromstopp',
  'elbil-vann-kjoring',
  'elbil-rust',
  'elbil-batteribyttemyte',
  'elbil-helse-stråling',
  'elbil-barnevennlig',
  'elbil-dyr-myte',
  'elbil-rekkevidde-myte',
  'elbil-kjedelig-kjore',
  'kan-elbil-taues',
  'elbil-lyd-fotgjengere',
  'elbil-faq',
  'elbil-kjop-sjekkliste',
  'elbil-forste-gang',
  'elbil-overgang-fra-fossil',
  'elbil-nybegynner',
  'elbil-fellesskap-forum',
  'elbil-ordbok',
  'elbil-oslo',
  'elbil-bergen',
  'elbil-trondheim',
  'elbil-stavanger',
  'elbil-tromso',
  'elbil-kristiansand',
  'elbil-drammen',
  'elbil-fredrikstad',
  'elbil-bodo',
  'elbil-alesund',
  'elbil-nordsjo-ruten',
  'elbil-lofoten',
  'elbil-nordkapp',
  'elbil-hardangervidda',
  'elbil-atlanterhavsvegen',
  'elbil-oslo-bergen',
  'elbil-oslo-trondheim',
  'elbil-oslo-stavanger',
  'elbil-sorlandet',
  'elbil-vestlandet',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date().toISOString()

  const pillarEntries: MetadataRoute.Sitemap = pillarPages.map((slug) => ({
    url: slug ? `${BASE_URL}/${slug}` : BASE_URL,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: slug === '' ? 1.0 : 0.9,
  }))

  const clusterEntries: MetadataRoute.Sitemap = clusterPages.map((slug) => ({
    url: `${BASE_URL}/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.8,
  }))

  const artikkelEntries: MetadataRoute.Sitemap = artikler.map((slug) => ({
    url: `${BASE_URL}/artikler/${slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }))

  return [...pillarEntries, ...clusterEntries, ...artikkelEntries]
}
